<a href="https://colab.research.google.com/github/Pavan6-c/-ICP-3/blob/main/ICP3_summer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1.Numpy

import numpy as np

# a. Create a random vector of size 15 with integers from 1 to 20
arr = np.random.randint(1, 21, size=15)
print("Original array:\n", arr)

# 1. Reshape the array to 3 by 5
reshaped_arr = arr.reshape(3, 5)
print("\nReshaped array (3x5):\n", reshaped_arr)

# 2. Print array shape
print("\nShape of the array:", reshaped_arr.shape)

# 3. Replace the max in each row with 0
for i in range(reshaped_arr.shape[0]):
    max_index = reshaped_arr[i].argmax()  # Get index of max in the row
    reshaped_arr[i][max_index] = 0        # Replace it with 0

print("\nArray after replacing max in each row with 0:\n", reshaped_arr)

Original array:
 [ 3 12  6 12 17  3 10 18  9  6  5 10 12 12 10]

Reshaped array (3x5):
 [[ 3 12  6 12 17]
 [ 3 10 18  9  6]
 [ 5 10 12 12 10]]

Shape of the array: (3, 5)

Array after replacing max in each row with 0:
 [[ 3 12  6 12  0]
 [ 3 10  0  9  6]
 [ 5 10  0 12 10]]


In [ ]:
#b
import numpy as np

# Create a 2D array of size 4x3 with 4-byte integers
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]], dtype=np.int32)

print("Array:\n", arr) #print the array

# Print the shape
print("\nShape of the array:", arr.shape)

# Print the type
print("Type of the array:", type(arr))

# Print the data type
print("Data type of the array elements:", arr.dtype)


Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Shape of the array: (4, 3)
Type of the array: <class 'numpy.ndarray'>
Data type of the array elements: int32


In [ ]:
#c
import numpy as np

# Define the square array
A = np.array([[3, -2],
              [1,  0]])

# Compute eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Display results
print("Eigenvalues:\n", eigenvalues)
print("\nRight Eigenvectors:\n", eigenvectors)


Eigenvalues:
 [2. 1.]

Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [ ]:
#d
import numpy as np

# Define the array
arr = np.array([[0, 1, 2],
                [3, 4, 5]])

# Compute the sum of the diagonal elements
diagonal_sum = np.trace(arr)

# Display the result
print("Sum of diagonal elements:", diagonal_sum)

Sum of diagonal elements: 4


In [ ]:
#e
import numpy as np

# Original 3x2 array
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])

print("Original array (3x2):\n", arr)

# Reshape to 2x3
reshaped_arr = arr.reshape(2, 3)

print("\nReshaped array (2x3):\n", reshaped_arr)

Original array (3x2):
 [[1 2]
 [3 4]
 [5 6]]

Reshaped array (2x3):
 [[1 2 3]
 [4 5 6]]
